language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit src/ --coverage-clover=build/coverage.clove

after_script:
  - if [ $(phpenv version-name) == "7.1" ]; wget https://scrutinizer-ci.com/ocular.phar -O build/ocular.phar ; fi
  - if [ $(phpenv version-name) == "7.1" ]; php build/ocular.phar code-coverage:upload --format=php-clover build/coverage.clover ; fi
