language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./bin/fix -v --dry-run --stop-on-violation
  - ./vendor/bin/phpunit src/ --coverage-clover=build/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar -O build/ocular.phar
  - php build/ocular.phar code-coverage:upload --format=php-clover build/coverage.clover
